application: broadcast-study 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(css|js))
  static_files: \1 
  upload: /(.*\.(css|js))

- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest

